### ISSUE TITLE
Suggestions for cleaning up this git repository

### ISSUE THREAD

**Issue by neuhaus** [arpruss/raspberryjammod#12]
Could you please move the models into a separate repository?
From what I can tell they are not directly related to the project, right?

When cloning the git repo, it's a 89MB download and uses up  155M of disk space.
There's a 90MB file in the `.git/objects/pack/` directory which probably consists of models.
And there's a 60MB `models` subdirectory.

Also `mcpipy` contains lots of (large) examples. What do you think about just keeping one or two small examples and moving the rest into their own repository?

The (cryptically named) directories `19`, `194` and `110` seem to contain the repository https://github.com/MinecraftForge/MinecraftForge (different branches?).

The directory `gpl-stuff/sunfish` contains a copy of https://github.com/thomasahle/sunfish
Something weird happened to the license file in that directory. It contains lots of entities.

The directory `src/main/java/org/java_websocket`
contains a copy (without LICENSE or attribution) of https://github.com/TooTallNate/Java-WebSocket

What do you think about using those repositories as a **git submodules**? That way you automatically get their fixes and improvements.

Once everything that doesn't belong to the core project is moved elsewhere there is less than 500kb of data (160kb of java source code) remaining. Much easier to dive into!

Thank you for building this project and for your consideration.

**Comment by arpruss** [comment]
It's a mess, I agree.

I use svn instead of git. I used git for a while and didn't like it as much as svn. I don't know if one can do submodules with svn.

The credits for the websocket module are in the root LICENSE file.

I fixed the sunfish license.

I want to have in place almost everything that's needed to produce the Windows .exe installer. That requires all the different versions of the mod (1.8x, 1.9, 1.9.4, 1.10 and 1.10.2). The one thing I don't include is Python binaries.

I suppose I could move the models directory to a separate repository. But wouldn't git still include them in .git so you could revert?

**Comment by arpruss** [comment]
I think I can't move the models directory to a separate project, actually, because I only got permission to include some of the models in *this* project.
