### ISSUE TITLE
Documentation/Info Request

### ISSUE THREAD

**Issue by julianrendell** [arpruss/raspberryjammod#2]
Hi there-

really like the work you've done with this, and the well written, extensive Instructible. I managed to use it + OpenCV to make a 'live TV' in Minecraft ;-)

I'm setting up a MineCraft teaching server, and to keep things fun and manageable I'm thinking of doing something like:

Bukkit (spigot?) + multiverse + backup + management plugins.

I'd like there to be several worlds: Introduction world, creative world, python world, etc.

I'm also trying to make it so that kids can replicate parts of this (relatively) easily at home.

So I'd like to use raspberryjammod on the server as they can set up the same at home.

I saw on a minecraft forum that you now support multiple worlds- e.g. nether, and overworld (which I only know about in name... I haven't played the game that much yet!) and that it should support other worlds as well.

So a few questions:

What are the other worlds? How do you set them up with a forge/original server?

Do you know if your scripts be used with the Bukkit RaspberryPiJuice plugin?
It seems your scripts (turtle drawing, etc) are more advanced... e.g. things like filled surfaces.  Is that in the python scripts or the plugin?

Do you have any thoughts of porting RaspberryJamMod to Bukkit?

Any thoughts or suggestions appreciated; I know what I want to build, but I'm finding the mixed history of all the moving pieces a bit hard to navigate!

Thanks in advance,

Julian

**Comment by arpruss** [comment]
1. Overworld is where you start in Minecraft. By default, a stock server will have Overworld, Nether and End.
2. Almost all my scripts should work with RaspberryJuice, though occasionally with reduced functionality. The vehicle and scan scripts are probably unusably slow with Juice (because Juice makes each call to world.getBlock*() take 0.05 seconds). The symmetry script won't work with Juice at all, because Juice doesn't let you monitor clicks with anything but a sword. That's all I can think of right now.
3. The additional stuff like turtle drawing is all in python. See drawing.py for surfaces.
4. No, I am not planning a Bukkit port. It is hard enough to keep three versions of RaspberryJam afloat: Minecraft desktop (with both server and client support), Android Minecraft PE, and Minetest.

**Comment by julianrendell** [comment]
Thanks for the quick reply!

I'd like to help you maintain this. What do you need help with?
